#pragma once

/**
 * @file TextureArray.h
 * @brief 2D texture array (VK_IMAGE_VIEW_TYPE_2D_ARRAY) for block face textures.
 *
 * Loads N PNG layers (one per block face) into a single device-local array image.
 * All layers must share the same width and height. A mip chain is generated by
 * linear blit-down to suppress minification shimmer on distant tiled geometry while
 * keeping the in-plane NEAREST filter for the crisp voxel look. The sampler uses
 * REPEAT addressing so per-block UVs (expressed in block units) tile correctly
 * across greedy-merged quads.
 *
 * An in-memory constructor is provided for atlases built from resized/generated
 * pixel data (e.g. the model skin atlas) without requiring equal-size source files.
 * @see docs/CODE_INDEX.md
 */

#include <vulkan/vulkan.h>

#include <string>
#include <vector>

namespace vg {

class VulkanContext;

// -----------------------------------------------------------------------------
//  TextureArray
// -----------------------------------------------------------------------------
//  A VK_IMAGE_VIEW_TYPE_2D_ARRAY texture: one image with N layers, one layer per
//  source PNG. Block faces index into it by layer (see BlockRegistry).
//
//  The sampler uses REPEAT addressing so that, combined with UVs expressed in
//  block units, each block tile of a greedy-merged quad shows one full copy of
//  the texture instead of the texture being stretched across the whole quad.
//
//  All source images must share the same dimensions (array layers must match).
//
//  A capped mip chain is built at load (linear blit-down per array layer) to kill
//  the minification shimmer/moiré on distant tiled tiles; the sampler stays NEAREST
//  in-plane for the crisp voxel look. See TextureArray.cpp.
//
//  TODO(future): a path for blocks that use custom models rather than cube-face
//  textures (e.g. a furnace) — those would register differently.
// -----------------------------------------------------------------------------
/**
 * @brief Device-local 2D array texture with mip chain and REPEAT sampler for block faces.
 */
class TextureArray {
public:
    // Loads `filenames` (resolved relative to `textureDir`) into the array. All
    // files must share dimensions.
    TextureArray(VulkanContext& ctx, const std::vector<std::string>& filenames,
                 const std::string& textureDir);
    // In-memory: each `layers[i]` is a width*height RGBA8 image (caller-resized so
    // they all match). For atlases built from arbitrary-size source images.
    TextureArray(VulkanContext& ctx, const std::vector<std::vector<unsigned char>>& layers,
                 int width, int height);
    ~TextureArray();

    TextureArray(const TextureArray&) = delete;
    TextureArray& operator=(const TextureArray&) = delete;

    [[nodiscard]] VkImageView view()    const { return view_; }
    [[nodiscard]] VkSampler   sampler() const { return sampler_; }

private:
    // Stage `pixels` (layerCount tightly-packed width*height RGBA8 images) into the
    // device-local array image + mip chain. Shared by both constructors.
    void uploadPixels(const std::vector<unsigned char>& pixels, int width, int height,
                      uint32_t layerCount);
    void createSampler();
    void generateMipmaps(int width, int height, uint32_t layerCount);
    static uint32_t mipLevelsFor(int width, int height);

    VulkanContext* ctx_ = nullptr;

    VkImage        image_     = VK_NULL_HANDLE;
    VkDeviceMemory memory_    = VK_NULL_HANDLE;
    VkImageView    view_      = VK_NULL_HANDLE;
    VkSampler      sampler_   = VK_NULL_HANDLE;
    uint32_t       mipLevels_ = 1;
};

} // namespace vg
