#!/usr/bin/env python3
"""Regenerate assets/colors.yaml from assets/colormap.png.

The colormap is a small grid of solid colour swatches. This reads them in row-
major order (left-to-right, top-to-bottom) and writes a name -> "#RRGGBB" YAML
map that vg::Palette loads at runtime.

Names come from scripts/color_names.txt (one name per swatch, same order); any
swatch without a name is written as color_NN. This keeps human-readable names
(e.g. "sky_blue", which the code looks up) stable when you re-paint the colormap
-- edit the names file, not the generated YAML.

Usage (from the repo root):  python scripts/gen_colors.py
Requires Pillow (pip install pillow).
"""
import os

try:
    from PIL import Image
except ImportError:
    raise SystemExit("This script needs Pillow:  pip install pillow")

HERE = os.path.dirname(__file__)
PNG = os.path.join(HERE, "..", "assets", "colormap.png")
YAML = os.path.join(HERE, "..", "assets", "colors.yaml")
NAMES = os.path.join(HERE, "color_names.txt")


def load_names():
    if not os.path.exists(NAMES):
        return []
    names = []
    with open(NAMES, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#"):
                names.append(line)
    return names


def load_swatches():
    im = Image.open(PNG).convert("RGBA")
    w, h = im.size
    px = im.load()
    return [(px[x, y][0], px[x, y][1], px[x, y][2]) for y in range(h) for x in range(w)]


def main():
    swatches = load_swatches()
    names = load_names()

    entries = []
    seen = set()
    for i, (r, g, b) in enumerate(swatches):
        name = names[i] if i < len(names) else "color_%02d" % i
        if name in seen:
            print("warning: duplicate name '%s' (swatch %d) overrides an earlier one" % (name, i))
        seen.add(name)
        entries.append((name, "#%02X%02X%02X" % (r, g, b)))

    width = max(len(n) for n, _ in entries) + 1
    with open(YAML, "w", encoding="utf-8") as f:
        f.write("# Named colour palette -- GENERATED by scripts/gen_colors.py from\n")
        f.write("# assets/colormap.png. Do not edit by hand; change the colormap or\n")
        f.write("# scripts/color_names.txt and re-run the script. Loaded by vg::Palette.\n\n")
        for name, hexv in entries:
            f.write("%-*s \"%s\"\n" % (width, name + ":", hexv))

    print("wrote %s (%d colours)" % (os.path.normpath(YAML), len(entries)))
    if len(names) < len(swatches):
        print("note: %d swatches had no name and were written as color_NN" %
              (len(swatches) - len(names)))


if __name__ == "__main__":
    main()
